export const PartnerTypes = {
  GET_PARTNERS: 'GET_PARTNERS',
  GET_PARTNER: 'GET_PARTNER',
  UPDATE_PARTNER: 'EDIT_PARTNER',
  ADD_PARTNER: 'ADD_PARTNER',
  DELETE_PARTNER: 'DELETE_PARTNER',
  PARTNER_LOADING: 'PARTNER_LOADING',
  PARTNERS_LOADING: 'PARTNERS_LOADING'
};

export const MemberTypes = {
  GET_MEMBERS: 'GET_MEMBERS',
  GET_MEMBER: 'GET_MEMBER',
  UPDATE_MEMBER: 'EDIT_MEMBER',
  ADD_MEMBER: 'ADD_MEMBER',
  DELETE_MEMBER: 'DELETE_MEMBER',
  MEMBER_LOADING: 'MEMBER_LOADING',
  MEMBERS_LOADING: 'MEMBERS_LOADING'
};

export const ExperiencesTypes = {
  GET_EXPERIENCES: 'GET_EXPERIENCES',
  GET_EXPERIENCE: 'GET_EXPERIENCE',
  UPDATE_EXPERIENCE: 'UPDATE_EXPERIENCE',
  ADD_EXPERIENCE: 'ADD_EXPERIENCE',
  DELETE_EXPERIENCE: 'DELETE_EXPERIENCE',
  EXPERIENCE_LOADING: 'EXPERIENCE_LOADING',
  EXPERIENCES_LOADING: 'EXPERIENCES_LOADING'
};

export const UserTypes = {
  GET_USER: 'GET_USER',
  UPDATE_USER: 'UPDATE_USER',
  ADD_USER: 'ADD_USER',
  DELETE_USER: 'DELETE_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER'
};

export const ErrorTypes = {
  GET_ERRORS: 'GET_ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS'
};
